### ISSUE TITLE
How to start Push-Server-0.12.0-capsule-fat.jar

### ISSUE THREAD

**Issue by mrFixener** [chrisdchristo/capsule-maven-plugin#52]
I have some problem while start Push-Server-0.12.0-capsule-fat.jar and I newbie in this project. 
This project with https://github.com/WhisperSystems/PushServer and based on capsule-maven-plugin .
It' s next message:

```
CAPSULE: Waiting for client to connect...
Failed to find Premain-Class manifest attribute in G:\PushServer\Push-Server-0.12.0-capsule-fat.jar
Error occurred during initialization of VM
agent library failed to init: instrument
CAPSULE: Client connection failed.
CAPSULE EXCEPTION: Accept timed out while processing null null: null
java.net.SocketTimeoutException: Accept timed out
at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
at java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
at java.net.PlainSocketImpl.accept(Unknown Source)
at java.net.ServerSocket.implAccept(Unknown Source)
at java.net.ServerSocket.accept(Unknown Source)
at Capsule.startServer(Capsule.java:1717)
at Capsule.launch0(Capsule.java:1378)
at Capsule.launch(Capsule.java:1351)
at Capsule.launch(Capsule.java:1280)
at Capsule.main0(Capsule.java:399)
at Capsule.main(Capsule.java:379)
CAPSULE: Closing comm
CAPSULE: Cleanup
```

Firstly I need to know why<br> 
    ...
    Failed to find Premain-Class manifest attribute in G:\PushServer\Push-Server-0.12.0-capsule-fat.jar
    Error occurred during initialization of VM
    agent library failed to init: instrument
    <br>...<br>
it happened?<br>
Any idea?
Thanks

**Comment by chrisdchristo** [comment]
The plugin version used is quite old. Can you please update to the latest version and see if you still get the problem.

**Comment by chrisdchristo** [comment]
Closed due to inactivity.
